// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowService provides window management functionality
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetAllProcessesWithWindows returns all processes that have visible windows (for debugging)
 */
export function GetAllProcessesWithWindows(): $CancellablePromise<$models.ProcessInfo[]> {
    return $Call.ByID(2930244488).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetApplicationProcesses returns only processes that have visible windows
 */
export function GetApplicationProcesses(): $CancellablePromise<$models.ProcessInfo[]> {
    return $Call.ByID(2260448076).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetWindowInfo gets the current size and position of a window
 */
export function GetWindowInfo(pid: number): $CancellablePromise<$models.WindowInfo | null> {
    return $Call.ByID(1821594991, pid).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * SetWindowPosition sets both position and size of a window
 */
export function SetWindowPosition(pid: number, x: number, y: number, width: number, height: number): $CancellablePromise<void> {
    return $Call.ByID(2191662852, pid, x, y, width, height);
}

/**
 * SetWindowSize sets the size of a window by process PID, keeping current position
 */
export function SetWindowSize(pid: number, width: number, height: number): $CancellablePromise<void> {
    return $Call.ByID(3510539758, pid, width, height);
}

// Private type creation functions
const $$createType0 = $models.ProcessInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.WindowInfo.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
